### ISSUE TITLE
iPhone app don't see Android Devices and vice-versa

### ISSUE THREAD

**Issue by rostislawko** [opentrace-community/opentrace-ios#16]
1. Setup BlueTrace protocol in Android and iOS applications
2. Android app doesn't see iPhones tracks, but see tracks from other Androids
3. iOS app doesn't see Androids tracks, but see track from other iPhones

What could be the problem? Maybe some misconfiguration? Please advise, what can I do to solve this problem

**Comment by achrinza** [comment]
Have you taken a look at https://github.com/opentrace-community/opentrace-android/issues/10#issuecomment-613130247?

**Comment by rostislawko** [comment]
> Have you taken a look at [opentrace-community/opentrace-android#10 (comment)](https://github.com/opentrace-community/opentrace-android/issues/10#issuecomment-613130247)?

Will check and respond! Thank you in advance!

PS. If it's a solution I propose to reflect it in README.md, because I'm sure that I'm not first person stucking on this issue!

**Comment by rinekri** [comment]
@rostislawko I absolutely agree with you, it should be pointed in the readme, because it isn't obvious at first sight. And it should same by default.

**Comment by rostislawko** [comment]
Basically, the problem indeed was in different SERVICE_UUID and V2_CHARACTERISTIC_ID. For those, who work on both iOS and Android applications, take this into account and provide equal values. It's better to use different SERVICE_UUID for different environments and V2_CHARACTERISTIC_ID should be same for all environments.

**Comment by BhavnaMohan5** [comment]
Hi
I have the same issue.Both the v2 id and service uuid are same for both the devices,still there is no handshake.Could there be anything else that we have to make sure about.Android to android is happening and ios to ios communication is also happening.But ios to android and vice versa are not happening.
