### ISSUE TITLE
plist files error

### ISSUE THREAD

**Issue by nosecc** [opentrace-community/opentrace-ios#21]
i have place the GoogleService-Info.plist as mentioned in the PROD and STG directory in Firebase but i am getting the errors below:

Looking for GoogleService-Info.plist in /Users/reza/iostracer/opentrace-ios/OpenTrace/OpenTrace/Firebase/STG/GoogleService-Info.plist
No Staging GoogleService-Info.plist found. Please ensure it's in the proper directory.
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by nosecc** [comment]
resolved

**Comment by eqenkhjin** [comment]
how to resolve?
