### ISSUE TITLE
app store rejection

### ISSUE THREAD

**Issue by muhamed297** [opentrace-community/opentrace-ios#28]
How can I get a License for bluetrace service, the GPL 3 licence is rejected by app store review team

**Comment by mkorcy** [comment]
It was rejected specifically for license? How are the other derivative teams using it?

**Comment by muhamed297** [comment]
> It was rejected specifically for license? How are the other derivative teams using it?

Yes , the GPL3 licence is limited , they may have to use more flexible licence like  MIT or Apache

**Comment by mkorcy** [comment]
@joelkek we're working on a derivative of OTC as well, and are very interested in this topic.
